name: Build
on: push

env: # shared paths for all builds, ref with: env.NAME
  CARGO_TERM_COLOR: always
  RNOTE_PATH: /d/a/rnote-build/rnote-build/rnote
  INSTALL_PATH: /d/a/rnote-build/rnote-build/install
  BIN_PATH: /d/a/rnote-build/rnote-build/install/bin

jobs:
  build:
    name: Build rnote

    runs-on: windows-latest

    # defaul msys2 shell
    defaults:
        run:
          shell: msys2 {0}

    steps:
      - name: Prepare
        uses: msys2/setup-msys2@v2
        with:
          architecture: x64
          update: ture 
          install: >-
            git
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-desktop-file-utils
            mingw-w64-x86_64-appstream-glib
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-poppler-data
            mingw-w64-x86_64-meson

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true
          override: true

      - name: Fetch rnote
        run: |
          git clone https://github.com/flxzt/rnote --depth=1 && cd rnote
          git submodule update --init --recursive
          pwd 

      - name: Build && Install
        run: |
          cd ${{ env.RNOTE_PATH }}
          meson setup --prefix=${{ env.INSTALL_PATH }} _mesonbuild
          meson compile -C _mesonbuild
          meson install -C _mesonbuild


      # finish build and upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: rnote-x86_64-pc-windows-gnu
          path: ${{ env.BIN_PATH }}
